//
// V1SeverityNumber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@available(*, deprecated, renamed: "OTLP.V1SeverityNumber")
typealias V1SeverityNumber = OTLP.V1SeverityNumber

extension OTLP {
	/** Possible values for LogRecord.SeverityNumber.   - SEVERITY_NUMBER_UNSPECIFIED: UNSPECIFIED is the default SeverityNumber, it MUST NOT be used. */

	// Enums are now numeric, per:
	// https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding
	// https://github.com/open-telemetry/opentelemetry-proto/blob/v1.8.0/opentelemetry/proto/logs/v1/logs.proto#L88
	enum V1SeverityNumber: Int, Codable {
		case unspecified = 0
		case trace = 1
		case trace2 = 2
		case trace3 = 3
		case trace4 = 4
		case debug = 5
		case debug2 = 6
		case debug3 = 7
		case debug4 = 8
		case info = 9
		case info2 = 10
		case info3 = 11
		case info4 = 12
		case warn = 13
		case warn2 = 14
		case warn3 = 15
		case warn4 = 16
		case error = 17
		case error2 = 18
		case error3 = 19
		case error4 = 20
		case fatal = 21
		case fatal2 = 22
		case fatal3 = 23
		case fatal4 = 24
	}
}
