// Created by ladd_vantol on 3/12/2025.
// Copyright © 2025 Airbnb Inc. All rights reserved.

// Automatically generated by bear make:logger
// See: https://git.musta.ch/airbnb/apps/blob/master/ios/_infra/docs/debug_logging.md

import os

let logger = Logger(subsystem: "com.airbnb.telemetry", category: "NautilusTelemetry")
